// AzBaku AutoImport — Tam dil sistemi (AZ / RU)
(function(){
var T={
// ===== NAV & FOOTER =====
'nav-about':['Haqqımızda','О нас'],
'nav-examples':['Nümunələr','Примеры'],
'nav-request':['Sifariş ver','Заказать'],
'nav-calc':['Kalkulyator','Калькулятор'],
'nav-faq':['FAQ','FAQ'],
'nav-contact':['Əlaqə','Контакты'],
'header-cta':['Sifariş ver','Заказать'],
'call-btn':['Zəng edin','Позвонить'],
'foot-desc':['ABŞ və Kanada auksionlarından Azərbaycana sifarişlə avtomobil idxalı.','Импорт автомобилей под заказ из аукционов США и Канады в Азербайджан.'],
'foot-nav':['Naviqasiya','Навигация'],
'foot-contact':['Əlaqə','Контакты'],
'foot-social':['Sosial','Соцсети'],
'foot-addr':['Bakı, Azərbaycan','Баку, Азербайджан'],
'foot-copy':['Şəffaf idxal, etibarlı proses.','Прозрачный импорт, надёжный процесс.'],
'bc-home':['Ana səhifə','Главная'],

// ===== INDEX =====
'hero-h1':['Siz sifariş verin,<br><em>biz tapıb gətirək.</em>','Вы заказываете,<br><em>мы находим и привозим.</em>'],
'hero-lead':['Sizin üçün ABŞ və Kanada auksionlarından dəqiq istədiyiniz avtomobili axtarır, alır və Bakıya qədər sığortalı çatdırırıq.','Мы ищем, покупаем и доставляем именно тот автомобиль, который вы хотите, с аукционов США и Канады до Баку со страховкой.'],
'hero-btn1':['Sifariş ver ›','Заказать ›'],
'hero-btn2':['Nümunələrə bax','Смотреть примеры'],
'trust-1-lbl':['uğurlu idxal','успешных импортов'],
'trust-2-val':['38–45 gün','38–45 дней'],
'trust-2-lbl':['orta müddət','средний срок'],
'trust-3-val':['Sığortalı','Застрахованная'],
'trust-3-lbl':['daşınma','доставка'],
'trust-4-val':['Gizli xərc yoxdur','Без скрытых расходов'],
'process-eye':['Prosesimiz','Наш процесс'],
'process-h2':['Auksiondan qapınıza qədər','От аукциона до вашей двери'],
'process-sub':['Hər addımda sizə məlumat veririk — avtomobili görmədən pul ödəmək narahatedicidir.','Мы информируем вас на каждом шаге — платить, не видя автомобиль, тревожно.'],
'st1-h':['Sifariş','Заказ'],'st1-p':['Marka, model, il və büdcənizi bildirin','Укажите марку, модель, год и бюджет'],
'st2-h':['Auksion','Аукцион'],'st2-p':['Copart, IAAI daxil olmaqla uyğun lotu tapırıq','Находим подходящий лот на Copart, IAAI и др.'],
'st3-h':['Alış','Покупка'],'st3-p':['Sizin təsdiqinizlə avtomobili qazanırıq','Выигрываем автомобиль с вашего подтверждения'],
'st4-h':['Daşınma','Доставка'],'st4-p':['Sığortalı konteyner ilə Bakı limanına','Застрахованным контейнером в порт Баку'],
'st5-h':['Təhvil','Передача'],'st5-p':['Gömrükdən keçir, açarlar sizdədir','Таможня пройдена, ключи у вас'],
'cases-eye':['Sübut','Доказательство'],
'cases-h2':['Bunları biz artıq gətirmişik','Мы уже привезли эти автомобили'],
'cases-sub':['Real qiymət və müddətlərlə keçmiş sifarişlər.','Прошлые заказы с реальными ценами и сроками.'],
'cases-btn':['Bütün nümunələrə bax →','Все примеры →'],
'paths-eye':['İki yol','Два пути'],
'paths-h2':['Necə başlamaq istəyirsiniz?','Как вы хотите начать?'],
'path1-h':['Dəqiq sifariş verin','Сделайте точный заказ'],
'path1-p':['Marka, model, il və büdcənizi bildirin. 24 saat ərzində uyğun variantlarla sizinlə əlaqə saxlayırıq.','Укажите марку, модель, год и бюджет. Мы свяжемся с вами в течение 24 часов с подходящими вариантами.'],
'path1-btn':['Sifariş formasını doldur','Заполнить форму заказа'],
'path2-h':['Auksion nümunələrinə baxın','Посмотрите примеры аукционов'],
'path2-p':['Hazırda auksionlarda olan seçilmiş lotlara baxın, bəyəndiyinizi bizə göstərin.','Посмотрите выбранные лоты на аукционах, покажите нам понравившийся.'],
'path2-btn':['Nümunə lotlara bax','Смотреть лоты'],
'why-eye':['Niyə AzBaku','Почему AzBaku'],
'why-h2':['Stokumuz yoxdur. Etibarımız var.','У нас нет склада. У нас есть доверие.'],
'why1-h':['Gizli xərc yoxdur','Без скрытых расходов'],
'why1-p':['Auksion, daşınma, gömrük və xidmət haqqı ayrıca göstərilir.','Аукцион, доставка, таможня и сервисный сбор указаны отдельно.'],
'why2-h':['Təsdiqsiz alış yoxdur','Никаких покупок без подтверждения'],
'why2-p':['Heç bir lot sizin razılığınız olmadan qazanılmır.','Ни один лот не выигрывается без вашего согласия.'],
'why3-h':['Real keçmiş sifarişlər','Реальные прошлые заказы'],
'why3-p':['Hər nümunə real qiymət və müddətlə göstərilir.','Каждый пример показан с реальной ценой и сроком.'],
'cta-eye':['Hazırsınız?','Готовы?'],
'cta-h2':['Hansı avtomobili axtarırsınız?','Какой автомобиль вы ищете?'],
'cta-p':['Formanı doldurun, 24 saat ərzində uyğun variantlarla geri dönüş edək.','Заполните форму, мы свяжемся с вами в течение 24 часов.'],
'cta-btn1':['Sifariş ver','Заказать'],
'delivered':['Təhvil verildi','Доставлено'],
'case-price':['Yekun qiymət','Итоговая цена'],
'case-days':['Müddət','Срок'],

// ===== EXAMPLES =====
'ex-eye':['Real idxal nümunələri','Реальные примеры импорта'],
'ex-h1':['Bunları biz artıq gətirmişik','Мы уже привезли эти автомобили'],
'ex-sub':['Hər nümunə real ölkədən, real qiymətlə göstərilir. Üzərinə klikləyərək tam bölgüyə baxın.','Каждый пример показан из реальной страны, по реальной цене. Нажмите для полной разбивки.'],
'ex-cta':['Tam məlumata bax →','Подробнее →'],
'ex-loading':['Yüklənir...','Загрузка...'],

// ===== EXAMPLE DETAIL =====
'det-country':['Mənşə ölkə','Страна происхождения'],
'det-days':['Ümumi müddət','Общий срок'],
'det-breakdown':['Qiymət bölgüsü','Разбивка стоимости'],
'det-auction':['Auksion qiyməti','Цена на аукционе'],
'det-shipping':['Daşınma (gəmi)','Доставка (море)'],
'det-customs':['Gömrük rüsumu','Таможенная пошлина'],
'det-service':['Xidmət haqqımız','Наш сервисный сбор'],
'det-total':['Yekun qiymət','Итоговая цена'],
'det-note':['Bu rəqəmlər real sifarişin bölgüsüdür.','Эти цифры — разбивка реального заказа.'],
'det-cta':['Oxşar avtomobil sifariş ver','Заказать похожий автомобиль'],
'det-nobind':['Öhdəlik yaratmır','Ни к чему не обязывает'],
'det-notfound':['Tapılmadı.','Не найдено.'],
'det-back':['Nümunələrə qayıt →','Вернуться к примерам →'],

// ===== REQUEST =====
'req-eye':['2 dəqiqə çəkir','Займёт 2 минуты'],
'req-h1':['Hansı avtomobili axtarırsınız?','Какой автомобиль вы ищете?'],
'req-sub':['Heç nə ödəmirsiniz — bu, sadəcə axtarış sorğusudur.','Вы ничего не платите — это просто поисковый запрос.'],
'req-leg1':['Avtomobil','Автомобиль'],
'req-leg1-sub':['Dəqiq bilmirsinizsə, təxmini yazın.','Если не знаете точно, напишите примерно.'],
'req-make':['Marka','Марка'],'req-model':['Model','Модель'],
'req-yearmin':['İl (min)','Год (от)'],'req-yearmax':['İl (maks)','Год (до)'],
'req-cond':['Vəziyyət','Состояние'],
'req-cond1':['Zədəsiz','Без повреждений'],'req-cond2':['Yüngül zədəli','Лёгкие повреждения'],'req-cond3':['Fərq etməz','Не важно'],
'req-mileage':['Maksimum yürüş (km)','Максимальный пробег (км)'],
'req-leg2':['Büdcə','Бюджет'],
'req-leg2-sub':['Yekun qiymətə auksion + daşınma + gömrük + xidmət haqqı daxildir.','В итоговую цену входят аукцион + доставка + таможня + сервисный сбор.'],
'req-min':['Minimum ($)','Минимум ($)'],'req-max':['Maksimum ($)','Максимум ($)'],
'req-leg3':['Əlaqə','Контакты'],
'req-leg3-sub':['24 saat ərzində əlaqə saxlayacağıq.','Мы свяжемся с вами в течение 24 часов.'],
'req-name':['Ad Soyad','Имя Фамилия'],'req-phone':['Telefon','Телефон'],
'req-notes':['Əlavə qeydlər','Дополнительные заметки'],
'req-notes-hint':['(istəyə görə)','(по желанию)'],
'req-submit':['Sorğunu göndər','Отправить запрос'],
'req-nobind':['Öhdəlik yaratmır','Ни к чему не обязывает'],
'req-side-h':['Sonra nə baş verir','Что происходит дальше'],
'req-s1':['24 saat ərzində zəng','Звонок в течение 24 часов'],
'req-s1p':['Sorğunuzu araşdırıb əlaqə saxlayırıq.','Мы изучим ваш запрос и свяжемся с вами.'],
'req-s2':['2-3 uyğun lot','2–3 подходящих лота'],
'req-s2p':['Tam vəziyyət hesabatı ilə variantlar göndəririk.','Отправим варианты с полным отчётом о состоянии.'],
'req-s3':['Siz qərar verirsiniz','Решение за вами'],
'req-s3p':['Təsdiqləyənə qədər heç nə ödəmirsiniz.','Вы ничего не платите до подтверждения.'],
'req-urgent':['Tələsikdirsə:','Если срочно:'],
'req-succ-h':['Sorğunuz qəbul edildi','Ваш запрос принят'],
'req-succ-p':['24 saat ərzində sizinlə əlaqə saxlayacağıq.','Мы свяжемся с вами в течение 24 часов.'],
'req-succ-btn':['Ana səhifəyə qayıt','Вернуться на главную'],
'err-make':['Marka daxil edin','Введите марку'],
'err-model':['Model daxil edin','Введите модель'],
'err-name':['Adınızı daxil edin','Введите ваше имя'],
'err-phone':['Telefon daxil edin','Введите телефон'],

// ===== CALCULATOR =====
'calc-eye':['Qiymət hesablama','Расчёт стоимости'],
'calc-h1':['Daşınma Kalkulyatoru','Калькулятор доставки'],
'calc-sub':['Auksiondan Bakıya qədər təxmini xərci hesablayın — nəticə dərhal görünəcək.','Рассчитайте примерную стоимость от аукциона до Баку — результат появится сразу.'],
'calc-h3':['Kalkulyator','Калькулятор'],
'calc-desc':['Sahələri doldurun, qiymət avtomatik hesablanacaq','Заполните поля, цена рассчитается автоматически'],
'calc-s1':['Auksion platformu','Аукционная площадка'],
'calc-s2':['Lokasiya (ştat/ölkə)','Локация (штат/страна)'],
'calc-s3':['Yükləmə portu','Порт погрузки'],
'calc-s3-hint':['Lokasiyaya görə avtomatik seçilir','Выбирается автоматически по локации'],
'calc-s4':['Auksion qiyməti ($)','Цена на аукционе ($)'],
'calc-s5':['Kateqoriya','Категория'],
'calc-s6':['Çatdırılma portu','Порт доставки'],
'calc-s7':['Buraxılış ili','Год выпуска'],
'calc-s7-hint':['Gömrük rüsumuna təsir edir','Влияет на таможенную пошлину'],
'calc-reset':['↺ Sıfırla','↺ Сбросить'],
'opt-auction':['— Auksion seçin —','— Выберите аукцион —'],
'opt-loc-first':['— Əvvəlcə auksion seçin —','— Сначала выберите аукцион —'],
'opt-loc':['— Lokasiya seçin —','— Выберите локацию —'],
'opt-port':['— Lokasiya seçildikdən sonra —','— После выбора локации —'],
'cat-sedan':['Sedan / Hatchback','Седан / Хэтчбек'],
'cat-suv':['SUV / Crossover','Внедорожник / Кроссовер'],
'cat-truck':['Truck / Pikap','Грузовик / Пикап'],
'cat-van':['Van / Minivan','Фургон / Минивэн'],
'cat-ev':['⚡ Elektrik (EV)','⚡ Электро (EV)'],
'cat-hybrid':['Hibrid','Гибрид'],
'cat-premium':['Premium / Lüks','Премиум / Люкс'],
'r-h3':['Qiymət bölgüsü','Разбивка стоимости'],
'r-auction':['Auksion qiyməti','Цена на аукционе'],
'r-fee':['Buyer fee','Комиссия аукциона'],
'r-inland':['ABŞ daxili daşınma','Доставка по США'],
'r-ocean':['Dəniz daşınması','Морская доставка'],
'r-customs':['Gömrük rüsumu (~)','Таможенная пошлина (~)'],
'r-service':['AzBaku xidmət haqqı','Сервисный сбор AzBaku'],
'r-total':['Yekun (təxmini)','Итого (примерно)'],
'r-note':['Bu rəqəmlər təxminidir (±10–15%). Dəqiq hesab üçün bizimlə əlaqə saxlayın.','Эти цифры приблизительные (±10–15%). Для точного расчёта свяжитесь с нами.'],
'r-cta':['Sifariş ver — dəqiq qiymət al','Заказать — узнать точную цену'],
'info1-h':['Poti daha sərfəlidir','Поти выгоднее'],
'info1-p':['Poti portu vasitəsilə daşıma adətən daha sürətli və ucuzdur.','Доставка через порт Поти обычно быстрее и дешевле.'],
'info2-h':['EV güzəştləri','Льготы для электромобилей'],
'info2-p':['Elektrik avtomobillər üçün gömrük rüsumunda xüsusi güzəştlər var.','Для электромобилей действуют специальные таможенные льготы.'],
'info3-h':['2–3 illik avtomobillər','Автомобили 2–3 лет'],
'info3-p':['Bu yaş aralığı gömrük baxımından ən əlverişlidir.','Этот возраст наиболее выгоден с точки зрения таможни.'],

// ===== FAQ =====
'faq-eye':['Tez-tez verilən suallar','Часто задаваемые вопросы'],
'faq-h1':['Suallarınıza Cavablar','Ответы на ваши вопросы'],
'faq-sub':['Auksion prosesindən gömrük rəsmiləşdirilməsinə qədər hər şeyi burada izah edirik.','Здесь мы объясняем всё — от процесса аукциона до таможенного оформления.'],
'faq-cat':['Kateqoriya','Категория'],
'faq-all':['Hamısı','Все'],
'faq-auction':['Auksion','Аукцион'],
'faq-shipping':['Daşıma','Доставка'],
'faq-customs':['Gömrük','Таможня'],
'faq-price':['Qiymət','Цена'],
'faq-tech':['Texniki','Техническое'],
'faq-cta-h':['Sualınız Cavablanmadımı?','Не нашли ответ?'],
'faq-cta-p':['Komandamız hər sualınıza cavab vermək üçün hazırdır.','Наша команда готова ответить на любой ваш вопрос.'],
'faq-sec-auction':['🔨 Auksion','🔨 Аукцион'],
'faq-sec-ship':['🚢 Daşıma','🚢 Доставка'],
'faq-sec-cust':['📋 Gömrük','📋 Таможня'],
'faq-sec-price':['💰 Qiymət','💰 Цена'],
'faq-sec-tech':['🔧 Texniki','🔧 Техническое'],
'q1':['Siz hansı auksionlarla işləyirsiniz?','С какими аукционами вы работаете?'],
'a1':['Biz əsasən ABŞ-ın ən böyük avtomobil auksionları ilə işləyirik: <strong>Copart</strong> (sığorta üzrə zərərli avtomobillər), <strong>IAAI</strong> (sığorta şirkətlərinin satışı), <strong>Manheim</strong> (diler avtomobilləri), <strong>Adesa</strong>, <strong>EDGE Pipeline</strong> və <strong>EnCar</strong> (Cənubi Koreya).','Мы работаем с крупнейшими автомобильными аукционами США: <strong>Copart</strong> (страховые повреждённые авто), <strong>IAAI</strong> (продажи страховых компаний), <strong>Manheim</strong> (дилерские авто), <strong>Adesa</strong>, <strong>EDGE Pipeline</strong> и <strong>EnCar</strong> (Южная Корея).'],
'q2':['Özüm lot seçə bilərəmmi?','Могу ли я сам выбрать лот?'],
'a2':['Hər iki variant mümkündür. <strong>Özünüz seçə bilərsiniz</strong> — lot nömrəsini bizə bildirirsiniz, biz tender edirik. Yaxud <strong>bizim komanda seçə bilər</strong>.','Возможны оба варианта. <strong>Вы можете выбрать сами</strong> — сообщаете нам номер лота, мы делаем ставку. Или <strong>наша команда подберёт</strong>.'],
'q3':['Tenderdən əvvəl avtomobilin vəziyyətini yoxlamaq olurmu?','Можно ли проверить состояние авто до торгов?'],
'a3':['Auksion saytlarında hər lot üçün <strong>20–40 foto</strong> mövcuddur. Ayrıca VIN nömrəsi ilə avtomobilin tarixçəsini yoxlaya bilərsiniz.','На аукционных сайтах для каждого лота есть <strong>20–40 фото</strong>. Также можно проверить историю авто по VIN-номеру.'],
'q4':['Tenderi udmasaq pul itirirəmmi?','Теряю ли я деньги, если не выиграю торги?'],
'a4':['Xeyr. Tenderdə udmadığınız halda heç bir ödəniş tələb olunmur. Limit qiymətinizi siz müəyyən edirsiniz.','Нет. Если вы не выиграли торги, никакой оплаты не требуется. Лимит цены устанавливаете вы.'],
'q5':['Tenderdən nə qədər sonra ödəniş edilməlidir?','Когда нужно оплатить после торгов?'],
'a5':['Lot qazanıldıqdan sonra adətən <strong>1–3 iş günü</strong> ərzində ödəniş tələb olunur.','После выигрыша лота оплата обычно требуется в течение <strong>1–3 рабочих дней</strong>.'],
'q6':['Yalnız zərərli avtomobil gətirirsinizmi?','Вы привозите только повреждённые автомобили?'],
'a6':['Xeyr. Zərərli (salvage) avtomobillərlə yanaşı, <strong>clean title</strong> — tam sağlam avtomobillər də gətiririk.','Нет. Помимо повреждённых (salvage), мы привозим и <strong>clean title</strong> — полностью исправные автомобили.'],
'q7':['Avtomobil Bakıya neçə günə çatır?','За сколько дней автомобиль доедет до Баку?'],
'a7':['Orta hesabla <strong>38–55 gün</strong>: auksion → liman 5–10 gün, limanda gözləmə 5–10 gün, dəniz yolu 25–35 gün.','В среднем <strong>38–55 дней</strong>: аукцион → порт 5–10 дней, ожидание в порту 5–10 дней, морской путь 25–35 дней.'],
'q8':['Hansı limanlardan daşıma edilir?','Из каких портов осуществляется доставка?'],
'a8':['ABŞ tərəfindən <strong>Baltimore, Houston, Los Angeles, New Jersey, Savannah, Seattle</strong>. Koreya üçün <strong>Busan</strong>. Gəliş: <strong>Poti (Gürcüstan)</strong> və ya <strong>Bakı Limanı</strong>.','Со стороны США: <strong>Балтимор, Хьюстон, Лос-Анджелес, Нью-Джерси, Саванна, Сиэтл</strong>. Для Кореи — <strong>Пусан</strong>. Прибытие: <strong>Поти (Грузия)</strong> или <strong>порт Баку</strong>.'],
'q9':['Daşıma zamanı avtomobil sığortalıdırmı?','Застрахован ли автомобиль при доставке?'],
'a9':['Bəli, <strong>tam dəniz sığortası</strong> daxildir. Yanğın, su basması, qəza — sığorta tərəfindən ödənilir.','Да, включена <strong>полная морская страховка</strong>. Пожар, затопление, авария — покрывается страховкой.'],
'q10':['Avtomobilimi real vaxtda izləyə bilərəmmi?','Могу ли я отслеживать автомобиль в реальном времени?'],
'a10':['Bəli. Gəmi şirkəti tracking nömrəsi verir. Komandamız hər mərhələdə WhatsApp ilə məlumatlandırır.','Да. Судоходная компания предоставляет трекинг-номер. Наша команда информирует на каждом этапе через WhatsApp.'],
'q11':['Poti yoxsa Bakı limanı — hansı daha yaxşıdır?','Поти или порт Баку — что лучше?'],
'a11':['<strong>Poti</strong> — daha sürətli və $300–$500 daha ucuz. <strong>Bakı Limanı</strong> — birbaşa, amma daha baha. Biz Potini tövsiyə edirik.','<strong>Поти</strong> — быстрее и на $300–$500 дешевле. <strong>Порт Баку</strong> — напрямую, но дороже. Мы рекомендуем Поти.'],
'q12':['Avtomobil konteynerə necə yüklənir?','Как автомобиль загружается в контейнер?'],
'a12':['Avtomobil <strong>20 və ya 40 fut konteynerə</strong> yerləşdirilir. Kiçik avtomobillər bəzən 2-li yüklənir. Xüsusi bərkitmə sistemləri ilə sabitlənir.','Автомобиль размещается в <strong>20- или 40-футовом контейнере</strong>. Малолитражки иногда грузятся по 2. Фиксируется специальными креплениями.'],
'q13':['Gömrük vergisi nə qədərdir?','Сколько составляет таможенная пошлина?'],
'a13':['Avtomobilin yaşı və CIF dəyərinə görə: 1–3 il ~15–20%, 4–7 il ~20–25%, 7+ il ~25–30%. Elektrik avtomobillər: 50% güzəşt.','Зависит от возраста и CIF-стоимости: 1–3 года ~15–20%, 4–7 лет ~20–25%, 7+ лет ~25–30%. Электромобили: льгота 50%.'],
'q14':['Gömrük prosesi necə işləyir?','Как проходит таможенный процесс?'],
'a14':['Avtomobil limana çatdıqdan sonra gömrük bəyannaməsi verilir. Komandamız bütün sənədləri hazırlayır.','После прибытия автомобиля в порт подаётся таможенная декларация. Наша команда готовит все документы.'],
'q15':['Gömrük neçə günə tamamlanır?','За сколько дней завершается таможня?'],
'a15':['Sənədlər tam olduqda adətən <strong>1–3 iş günü</strong>.','При полном комплекте документов обычно <strong>1–3 рабочих дня</strong>.'],
'q16':['Salvage title olan avtomobil qeydiyyata alınırmı?','Регистрируется ли авто с salvage title?'],
'a16':['Bəli. Gömrükdən sonra avtomobil texniki baxışdan keçirilir. Standartlara cavab verdikdə qeydiyyat rəsmiləşdirilir.','Да. После таможни автомобиль проходит техосмотр. При соответствии стандартам оформляется регистрация.'],
'q17':['Hansı sənədlər tələb olunur?','Какие документы требуются?'],
'a17':['Müştəridən: <strong>şəxsiyyət vəsiqəsi, FİN kod, ünvan</strong>. Title, Bill of Lading, sığorta və bəyannamə bizim tərəfimizdən hazırlanır.','От клиента: <strong>удостоверение личности, FIN-код, адрес</strong>. Title, Bill of Lading, страховка и декларация готовятся нами.'],
'q18':['Ümumi xərclərə nələr daxildir?','Что входит в общие расходы?'],
'a18':['Auksion lot qiyməti, buyer fee (5–12%), ABŞ daxili daşıma ($250), dəniz daşıma, sığorta, gömrük, AzBaku xidmət haqqı ($450).','Цена лота, комиссия аукциона (5–12%), доставка по США ($250), морская доставка, страховка, таможня, сервисный сбор AzBaku ($450).'],
'q19':['Kalkulyator nə dərəcədə dəqiqdir?','Насколько точен калькулятор?'],
'a19':['Kalkulyator <strong>təxmini rəqəm</strong> verir — ±10–15% fərq ola bilər.','Калькулятор даёт <strong>приблизительную цифру</strong> — возможна разница ±10–15%.'],
'q20':['Ödəniş necə edilir?','Как производится оплата?'],
'a20':['Adətən <strong>2 mərhələdə</strong>: ilkin ödəniş (tenderdən əvvəl) + son ödəniş (Bakıya gəldikdə). Bank köçürməsi, nağd və kart qəbul edilir.','Обычно <strong>в 2 этапа</strong>: предоплата (до торгов) + окончательный расчёт (по прибытии в Баку). Принимаем банковский перевод, наличные и карту.'],
'q21':['Neçə illik avtomobillər gətirilir?','Автомобили каких годов вы привозите?'],
'a21':['Heç bir il məhdudiyyəti yoxdur. Lakin gömrük vergisi üçün avtomobilin yaşı vacibdir.','Ограничений по годам нет. Однако возраст автомобиля важен для расчёта таможенной пошлины.'],
'q22':['VIN nömrəsi ilə nə yoxlamaq olar?','Что можно проверить по VIN-номеру?'],
'a22':['Qəza tarixi, odometer qeydi, əvvəlki sahiblər, servis tarixi, title növü, recall statusu.','История аварий, показания одометра, предыдущие владельцы, история обслуживания, тип title, статус отзывов.'],
'q23':['Elektrik avtomobilləri gətirmək mümkündürmü?','Можно ли привезти электромобиль?'],
'a23':['Bəli, Tesla, Rivian, Lucid gətiririk. Batareya vəziyyəti yoxlanmalıdır, gömrükdə ~50% güzəşt var.','Да, привозим Tesla, Rivian, Lucid. Нужно проверить состояние батареи, на таможне льгота ~50%.'],
'q24':['Zərərli avtomobili bərpa etmək nə qədər başa gəlir?','Сколько стоит восстановление повреждённого авто?'],
'a24':['Yüngül: 500–1,500 AZN. Orta: 2,000–5,000 AZN. Ağır: 5,000–12,000 AZN.','Лёгкие: 500–1,500 AZN. Средние: 2,000–5,000 AZN. Тяжёлые: 5,000–12,000 AZN.'],
'q25':['Avtomobil gözlədiyimdən fərqlidirsə nə etmək olar?','Что делать, если автомобиль отличается от ожидаемого?'],
'a25':['Auksion alışları geri qaytarılmır. Buna görə tenderdən əvvəl şəkilləri və VIN tarixçəsini diqqətlə yoxlayın.','Аукционные покупки возврату не подлежат. Поэтому внимательно проверяйте фото и историю VIN до торгов.'],

// ===== ABOUT =====
'ab-eye':['Biz kimik','Кто мы'],
'ab-sub':['ABŞ və Kanada auksionlarından Azərbaycana avtomobil gətirən etibarlı tərəfdaşınız.','Ваш надёжный партнёр по импорту автомобилей из аукционов США и Канады в Азербайджан.'],
'ab-story-eye':['Hekayəmiz','Наша история'],
'ab-story-h':['Şəffaflıq üzərinə qurulmuş biznes','Бизнес, построенный на прозрачности'],
'ab-p1':['AzBaku AutoImport olaraq biz ABŞ və Kanada auksionlarından Azərbaycana avtomobil idxalı ilə məşğuluq. Bizim öz avtoparkımız yoxdur — biz sizin istədiyiniz avtomobili tapır, alır və Bakıya qədər sığortalı şəkildə çatdırırıq.','AzBaku AutoImport занимается импортом автомобилей из аукционов США и Канады в Азербайджан. У нас нет собственного автопарка — мы находим, покупаем и доставляем нужный вам автомобиль до Баку со страховкой.'],
'ab-p2':['Hər addımda şəffaflıq prinsipimizdir: auksion qiyməti, daşınma, gömrük rüsumu və xidmət haqqı — hər bir xərc ayrıca göstərilir. Gizli ödəniş yoxdur.','Прозрачность — наш принцип на каждом этапе: цена аукциона, доставка, таможенная пошлина и сервисный сбор — каждый расход указан отдельно. Скрытых платежей нет.'],
'ab-p3':['Copart, IAAI, Manheim, Adesa, EDGE Pipeline və EnCar auksionları ilə birbaşa işləyirik. Sertifikatlı agentlərimiz sizin adınızdan ən optimal qiymətlə tender edir.','Мы работаем напрямую с аукционами Copart, IAAI, Manheim, Adesa, EDGE Pipeline и EnCar. Наши сертифицированные агенты делают ставки от вашего имени по оптимальной цене.'],
'ab-stat1':['Uğurlu idxal','Успешных импортов'],
'ab-stat2':['Gün orta müddət','Дней средний срок'],
'ab-stat3':['Auksion platformu','Аукционных площадок'],
'ab-stat4':['Sığortalı daşınma','Застрахованная доставка'],
'ab-val-eye':['Dəyərlərimiz','Наши ценности'],
'ab-val-h':['Niyə AzBaku?','Почему AzBaku?'],
'ab-val-sub':['Hər müştəri ilə uzunmüddətli əməkdaşlıq qurmaq istəyirik. Bu dəyərlər bizim əsasımızdır.','Мы хотим построить долгосрочное сотрудничество с каждым клиентом. Эти ценности — наша основа.'],
'ab-v1-h':['Şəffaflıq','Прозрачность'],
'ab-v1-p':['Hər xərc ayrıca göstərilir — auksion, daşınma, gömrük, xidmət haqqı. Gizli ödəniş yoxdur.','Каждый расход указан отдельно — аукцион, доставка, таможня, сервисный сбор. Скрытых платежей нет.'],
'ab-v2-h':['Təsdiqsiz alış yoxdur','Никаких покупок без подтверждения'],
'ab-v2-p':['Heç bir lot sizin razılığınız olmadan qazanılmır. Limit qiymətini siz müəyyən edirsiniz.','Ни один лот не выигрывается без вашего согласия. Лимит цены устанавливаете вы.'],
'ab-v3-h':['Sığortalı daşınma','Застрахованная доставка'],
'ab-v3-p':['Bütün avtomobillər tam dəniz sığortası ilə daşınır.','Все автомобили перевозятся с полной морской страховкой.'],
'ab-v4-h':['Real nümunələr','Реальные примеры'],
'ab-v4-p':['Hər bir keçmiş idxalımızı real qiymət və müddətlə göstəririk.','Мы показываем каждый прошлый импорт с реальной ценой и сроком.'],
'ab-v5-h':['Sürətli proses','Быстрый процесс'],
'ab-v5-p':['Auksion tenderindən Bakıya təhvilə qədər orta 38–45 gün.','От торгов до передачи в Баку в среднем 38–45 дней.'],
'ab-v6-h':['Əlverişli qiymət','Выгодная цена'],
'ab-v6-p':['Birbaşa auksionla işləyirik, vasitəçi yoxdur. Xidmət haqqımız sabitdir — $450.','Работаем напрямую с аукционами, без посредников. Наш сервисный сбор фиксированный — $450.'],
'ab-how-eye':['Proses','Процесс'],
'ab-how-h':['Necə işləyir?','Как это работает?'],
'ab-cta-h':['Gəlin birlikdə başlayaq','Давайте начнём вместе'],
'ab-cta-p':['Formanı doldurun, 24 saat ərzində uyğun variantlarla geri dönüş edək.','Заполните форму, мы свяжемся с вами в течение 24 часов.']
};

var lang = localStorage.getItem('azbaku_lang') || 'az';
var idx = function(){return lang==='ru'?1:0;};

function apply(l){
  lang=l; localStorage.setItem('azbaku_lang',l);
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    var k=el.getAttribute('data-i18n');
    if(T[k]) el.innerHTML=T[k][idx()];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(function(el){
    var k=el.getAttribute('data-i18n-ph');
    if(T[k]) el.placeholder=T[k][idx()];
  });
  var b=document.getElementById('langToggle');
  if(b) b.innerHTML = l==='az'
    ? '<img src="https://flagcdn.com/24x18/ru.png" style="width:18px;height:13px;border-radius:2px;"> RU'
    : '<img src="https://flagcdn.com/24x18/az.png" style="width:18px;height:13px;border-radius:2px;"> AZ';
  document.documentElement.lang=l;
  window.dispatchEvent(new CustomEvent('langchange',{detail:{lang:l}}));
}

function init(){
  var b=document.getElementById('langToggle');
  if(b) b.addEventListener('click',function(){apply(lang==='az'?'ru':'az');});
  apply(lang);
}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init);
else init();

window.azbakuLang={apply:apply,get:function(){return lang;},t:function(k){return T[k]?T[k][idx()]:'';}};
})();
