-- 'Bütün Mətnlər' tabı üçün 144 mətnin ilkin dəyərləri
-- Hər sətir mövcud saytda görünən HAZIRKI mətndir — heç nə vizual olaraq dəyişmir,
-- sadəcə admin paneldə redaktə edilə bilən hala gətirilir.

INSERT INTO site_settings (skey, svalue) VALUES
('txt_hero_h1','Siz sifariş verin,'),
('txt_hero_lead','Sizin üçün ABŞ və Kanada auksionlarından dəqiq istədiyiniz avtomobili axtarır, alır və Bakıya qədər sığortalı çatdırırıq.'),
('txt_hero_btn1','Sifariş ver ›'),
('txt_hero_btn2','Nümunələrə bax'),
('txt_why1_h','Gizli xərc yoxdur'),
('txt_process_eye','Prosesimiz'),
('txt_process_h2','Auksiondan qapınıza qədər'),
('txt_process_sub','Hər addımda sizə məlumat veririk — avtomobili görmədən pul ödəmək narahatedicidir.'),
('txt_st1_h','Sifariş'),
('txt_st2_h','Auksion'),
('txt_st3_h','Alış'),
('txt_st4_h','Daşınma'),
('txt_st5_h','Təhvil'),
('txt_cases_eye','Sübut'),
('txt_cases_h2','Bunları biz artıq gətirmişik'),
('txt_cases_sub','Real qiymət və müddətlərlə keçmiş sifarişlər.'),
('txt_delivered','Təhvil verildi'),
('txt_case_price','Yekun qiymət'),
('txt_case_days','Müddət'),
('txt_cases_btn','Bütün nümunələrə bax →'),
('txt_paths_eye','İki yol'),
('txt_paths_h2','Necə başlamaq istəyirsiniz?'),
('txt_path1_h','Dəqiq sifariş verin'),
('txt_path1_p','Marka, model, il və büdcənizi bildirin. 24 saat ərzində uyğun variantlarla sizinlə əlaqə saxlayırıq.'),
('txt_path1_btn','Sifariş formasını doldur'),
('txt_path2_h','Auksion nümunələrinə baxın'),
('txt_path2_p','Hazırda auksionlarda olan seçilmiş lotlara baxın, bəyəndiyinizi bizə göstərin.'),
('txt_path2_btn','Nümunə lotlara bax'),
('txt_why_eye','Niyə AzBaku'),
('txt_why_h2','Stokumuz yoxdur. Etibarımız var.'),
('txt_why1_p','Auksion, daşınma, gömrük və xidmət haqqı ayrıca göstərilir.'),
('txt_why2_h','Təsdiqsiz alış yoxdur'),
('txt_why2_p','Heç bir lot sizin razılığınız olmadan qazanılmır.'),
('txt_why3_h','Real keçmiş sifarişlər'),
('txt_why3_p','Hər nümunə real qiymət və müddətlə göstərilir.'),
('txt_cta_eye','Hazırsınız?'),
('txt_cta_h2','Hansı avtomobili axtarırsınız?'),
('txt_cta_p','Formanı doldurun, 24 saat ərzində uyğun variantlarla geri dönüş edək.'),
('txt_call_btn','Zəng edin'),
('txt_foot_desc','ABŞ və Kanada auksionlarından Azərbaycana sifarişlə avtomobil idxalı.'),
('txt_foot_nav','Naviqasiya'),
('txt_foot_addr','Bakı, Azərbaycan'),
('txt_foot_social','Sosial'),
('txt_foot_copy','Şəffaf idxal, etibarlı proses.'),
('txt_bc_home','Ana səhifə'),
('txt_ab_eye','Biz kimik'),
('txt_ab_h1','AzBaku AutoImport'),
('txt_ab_sub','ABŞ və Kanada auksionlarından Azərbaycana avtomobil gətirən etibarlı tərəfdaşınız.'),
('txt_ab_story_eye','Hekayəmiz'),
('txt_ab_story_h','Şəffaflıq üzərinə qurulmuş biznes'),
('txt_ab_p1','AzBaku AutoImport olaraq biz ABŞ və Kanada auksionlarından Azərbaycana avtomobil idxalı ilə məşğuluq. Bizim öz avtoparkımız yoxdur — biz sizin istədiyiniz avtomobili tapır, alır və Bakıya qədər sığortalı şəkildə çatdırırıq.'),
('txt_ab_p2','Hər addımda şəffaflıq prinsipimizdir: auksion qiyməti, daşınma, gömrük rüsumu və xidmət haqqı — hər bir xərc ayrıca göstərilir. Gizli ödəniş yoxdur.'),
('txt_ab_p3','Copart, IAAI, Manheim, Adesa, EDGE Pipeline və EnCar auksionları ilə birbaşa işləyirik. Sertifikatlı agentlərimiz sizin adınızdan ən optimal qiymətlə tender edir.'),
('txt_ab_stat1','Uğurlu idxal'),
('txt_ab_stat2','Gün orta müddət'),
('txt_ab_stat3','Auksion platformu'),
('txt_ab_stat4','Sığortalı daşınma'),
('txt_ab_val_eye','Dəyərlərimiz'),
('txt_ab_val_h','Niyə AzBaku?'),
('txt_ab_val_sub','Hər müştəri ilə uzunmüddətli əməkdaşlıq qurmaq istəyirik. Bu dəyərlər bizim əsasımızdır.'),
('txt_ab_how_eye','Proses'),
('txt_ab_how_h','Necə işləyir?'),
('txt_ab_cta_h','Gəlin birlikdə başlayaq'),
('txt_ab_cta_p','Formanı doldurun, 24 saat ərzində uyğun variantlarla geri dönüş edək.'),
('txt_ex_eye','Real idxal nümunələri'),
('txt_ex_h1','Bunları biz artıq gətirmişik'),
('txt_ex_sub','Hər nümunə real ölkədən, real qiymətlə göstərilir. Üzərinə klikləyərək tam bölgüyə baxın.'),
('txt_det_notfound','Tapılmadı.'),
('txt_det_back','Nümunələrə qayıt →'),
('txt_det_country','Mənşə ölkə'),
('txt_det_days','Ümumi müddət'),
('txt_det_breakdown','Qiymət bölgüsü'),
('txt_det_auction','Auksion qiyməti'),
('txt_det_shipping','Daşınma (gəmi)'),
('txt_det_customs','Gömrük rüsumu'),
('txt_det_service','Xidmət haqqımız'),
('txt_det_total','Yekun qiymət'),
('txt_det_note','Bu rəqəmlər real sifarişin bölgüsüdür.'),
('txt_det_cta','Oxşar avtomobil sifariş ver'),
('txt_det_nobind','Öhdəlik yaratmır'),
('txt_req_eye','2 dəqiqə çəkir'),
('txt_req_h1','Hansı avtomobili axtarırsınız?'),
('txt_req_sub','Heç nə ödəmirsiniz — bu, sadəcə axtarış sorğusudur.'),
('txt_req_leg1','Avtomobil'),
('txt_req_leg1_sub','Dəqiq bilmirsinizsə, təxmini yazın.'),
('txt_err_make','Marka daxil edin'),
('txt_err_model','Model daxil edin'),
('txt_req_yearmin','İl (min)'),
('txt_req_yearmax','İl (maks)'),
('txt_req_cond','Vəziyyət'),
('txt_req_cond1','Zədəsiz'),
('txt_req_cond2','Yüngül zədəli'),
('txt_req_cond3','Fərq etməz'),
('txt_req_mileage','Maksimum yürüş (km)'),
('txt_req_leg2','Büdcə'),
('txt_req_leg2_sub','Yekun qiymətə auksion + daşınma + gömrük + xidmət haqqı daxildir.'),
('txt_req_min','Minimum ($)'),
('txt_req_max','Maksimum ($)'),
('txt_req_leg3_sub','24 saat ərzində əlaqə saxlayacağıq.'),
('txt_err_name','Adınızı daxil edin'),
('txt_err_phone','Telefon daxil edin'),
('txt_req_notes','Əlavə qeydlər'),
('txt_req_notes_hint','(istəyə görə)'),
('txt_req_submit','Sorğunu göndər'),
('txt_req_nobind','Öhdəlik yaratmır'),
('txt_req_succ_h','Sorğunuz qəbul edildi'),
('txt_req_succ_p','24 saat ərzində sizinlə əlaqə saxlayacağıq.'),
('txt_req_succ_btn','Ana səhifəyə qayıt'),
('txt_req_side_h','Sonra nə baş verir'),
('txt_req_s1','24 saat ərzində zəng'),
('txt_req_s1p','Sorğunuzu araşdırıb əlaqə saxlayırıq.'),
('txt_req_s2','2-3 uyğun lot'),
('txt_req_s3','Siz qərar verirsiniz'),
('txt_req_s3p','Təsdiqləyənə qədər heç nə ödəmirsiniz.'),
('txt_req_urgent','Tələsikdirsə:'),
('txt_calc_eye','Qiymət hesablama'),
('txt_calc_h1','Daşınma Kalkulyatoru'),
('txt_calc_sub','Auksiondan Bakıya qədər təxmini xərci hesablayın — nəticə dərhal görünəcək.'),
('txt_calc_desc','Sahələri doldurun, qiymət avtomatik hesablanacaq'),
('txt_opt_auction','— Auksion seçin —'),
('txt_opt_loc_first','— Əvvəlcə auksion seçin —'),
('txt_calc_s3_hint','Lokasiyaya görə avtomatik seçilir'),
('txt_calc_reset','↺ Sıfırla'),
('txt_r_h3','Qiymət bölgüsü'),
('txt_r_auction','Auksion qiyməti'),
('txt_r_fee','Buyer fee'),
('txt_r_inland','ABŞ daxili daşınma'),
('txt_r_ocean','Dəniz daşınması'),
('txt_r_total','Yekun (təxmini)'),
('txt_r_note','Bu rəqəmlər təxminidir (±10–15%). Dəqiq hesab üçün bizimlə əlaqə saxlayın.'),
('txt_r_cta','Sifariş ver — dəqiq qiymət al'),
('txt_info1_h','Poti daha sərfəlidir'),
('txt_info1_p','Poti portu vasitəsilə daşıma adətən daha sürətli və ucuzdur.'),
('txt_info2_h','EV güzəştləri'),
('txt_info3_h','2–3 illik avtomobillər'),
('txt_info3_p','Bu yaş aralığı gömrük baxımından ən əlverişlidir.'),
('txt_faq_eye','Tez-tez verilən suallar'),
('txt_faq_cat','Kateqoriya'),
('txt_faq_all','Hamısı'),
('txt_faq_auction','Auksion'),
('txt_faq_shipping','Daşıma'),
('txt_faq_customs','Gömrük'),
('txt_faq_price','Qiymət'),
('txt_faq_tech','Texniki')
ON DUPLICATE KEY UPDATE svalue=svalue;